name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      # Spin up a postgresql container for testing
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgresql://test:test@localhost:5432/test" > .env.test
          echo "NODE_ENV=test" >> .env.test

      - name: Run Prisma Generate
        run: npx prisma generate

      - name: Run Prisma Migrate
        run: npx prisma migrate dev --name init --schema=./prisma/schema.prisma --skip-generate

      - name: Run Linting
        run: npm run lint

      - name: Run Type Check
        run: npm run typecheck

      - name: Run Tests
        run: npm test
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/test
          NODE_ENV: test
          NEXTAUTH_SECRET: test-secret
          NEXTAUTH_URL: http://localhost:3000
